version: "3.9"
services:
  reverse-proxy:
    image: traefik:v2.9
    ports:
      - "80:80"
      - "8081:8080"
    restart: always
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  fastapi:
    build: .
    command: > 
      sh -c "aerich upgrade && uvicorn src.main:app --proxy-headers --host 0.0.0.0 --port 8000"
    container_name: game-pass-library-api
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
  db:
    image: postgres:14.5
    restart: always
    user: postgres
    container_name: game-pass-library-db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  default:
    name: game-library-network
